
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package esercitazione4;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CHAR_CONST = 35;
  public static final int POW = 42;
  public static final int CHAR = 12;
  public static final int GE = 49;
  public static final int UMINUS = 11;
  public static final int INTEGER_CONST = 54;
  public static final int INTEGER = 9;
  public static final int SEMI = 3;
  public static final int OUT = 15;
  public static final int MINUS = 39;
  public static final int FOR = 16;
  public static final int WRITE = 24;
  public static final int NOT = 52;
  public static final int AND = 50;
  public static final int LT = 46;
  public static final int RPAR = 27;
  public static final int OR = 51;
  public static final int BOOL = 8;
  public static final int COMMA = 4;
  public static final int DIV = 41;
  public static final int PLUS = 38;
  public static final int LOOP = 22;
  public static final int ASSIGN = 31;
  public static final int MAIN = 2;
  public static final int IF = 17;
  public static final int WRITELN = 25;
  public static final int ID = 33;
  public static final int LE = 47;
  public static final int EOF = 0;
  public static final int RETURN = 32;
  public static final int TRUE = 36;
  public static final int error = 1;
  public static final int PIPE = 5;
  public static final int VOID = 13;
  public static final int EQ = 44;
  public static final int LBRACK = 28;
  public static final int REAL = 10;
  public static final int TIMES = 40;
  public static final int COLON = 30;
  public static final int ELSE = 19;
  public static final int READ = 23;
  public static final int RBRACK = 29;
  public static final int TO = 21;
  public static final int WHILE = 20;
  public static final int STR_CONCAT = 43;
  public static final int REAL_CONST = 34;
  public static final int THEN = 18;
  public static final int NE = 45;
  public static final int LPAR = 26;
  public static final int STRING = 7;
  public static final int DEF = 14;
  public static final int FALSE = 37;
  public static final int STRING_CONST = 53;
  public static final int GT = 48;
  public static final int VAR = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "SEMI",
  "COMMA",
  "PIPE",
  "VAR",
  "STRING",
  "BOOL",
  "INTEGER",
  "REAL",
  "UMINUS",
  "CHAR",
  "VOID",
  "DEF",
  "OUT",
  "FOR",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "TO",
  "LOOP",
  "READ",
  "WRITE",
  "WRITELN",
  "LPAR",
  "RPAR",
  "LBRACK",
  "RBRACK",
  "COLON",
  "ASSIGN",
  "RETURN",
  "ID",
  "REAL_CONST",
  "CHAR_CONST",
  "TRUE",
  "FALSE",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "POW",
  "STR_CONCAT",
  "EQ",
  "NE",
  "LT",
  "LE",
  "GT",
  "GE",
  "AND",
  "OR",
  "NOT",
  "STRING_CONST",
  "INTEGER_CONST"
  };
}

